Disable win-64 R3.5 build
The build is broken because devtools or one of its dependecies seem to be
currently broken:

> devtools::install()
Installing catboost
Error: 'setInternet2' is defunct.
See help("Defunct")
Execution halted
(C:\bld\r-catboost_1540624583274\_h_env) C:\bld\r-catboost_1540624583274\work>IF 1 NEQ 0 exit 1